### PR TITLE
Extensions

### PR DESCRIPTION
**Pull request by bonifaido**
Deployment, Job, PersistentVolume

### CODE REVIEW

**Comment by bonifaido** [comment]
I have changed the Dockerfile to build from the current working directory, because it used the upstream repo

**Comment by sebgoa** [comment]
Great, lgtm @ngtuna what do you think

@bonifaido FWIW we are not developing kubewatch much these days as we focus on kubeless. you sent us some PR there, email me if you want to discuss what you are doing, I am curious :)

**Comment by ngtuna** [comment]
LGTM. Although the controller and k8s client are a bit out-dated but they still work really well in case of kubewatch. Feel free to merge it. Thanks for the patches these few days recently @bonifaido 🥇

**Comment by bonifaido** [comment]
Nothing special, I just put together a semi automatic release workflow and kubewatch was sending the notifications to Slack. Kubeless, I just played it with it :)
Should I update the k8s client as well, or after you merge this one?

**Comment by ngtuna** [comment]
I am gonna merge this. For updating k8s client, that's great to see kubewatch can leverage client-go and work better with recent k8s releases so we are happy to see one more PR from you :-)

**Pull request merged**
