### PR TITLE
WIP: refactor kubewatch cli with cobra

### PR DESCRIPTION
**Pull request by ngtuna**
It's still in progress. 
Ref: #42 

I intend to struct kubewatch cli like this:

```console
$ kubewatch --help
A watcher for Kubernetes.

Usage:
  kubewatch [flags]
  kubewatch [command]

Available Commands:
  config      config modifies kubewatch configuration

$ kubewatch config --help
config modifies kubewatch configuration

Usage:
  kubewatch config SUBCOMMAND [flags]
  kubewatch config [command]

Available Commands:
  resource    specific resources to be watched
  slack       specific slack configuration

Global Flags:
      --config string                  config file (default is $HOME/.kubewatch.yaml)

$ kubewatch config slack --help
specific slack configuration

Usage:
  kubewatch config slack FLAG [flags]

Flags:
  -c, --channel string   Specify slack channel
  -t, --token string     Specify slack token

Global Flags:
      --config string                  config file (default is $HOME/.kubewatch.yaml)

$ kubewatch config resource --help
specific resources to be watched

Usage:
  kubewatch config resource FLAG [flags]

Flags:
      --deployments   watch for deployments
      --po            watch for pods
      --rc            watch for replication controllers
      --rs            watch for replicasets
      --svc           watch for services

Global Flags:
      --config string                  config file (default is $HOME/.kubewatch.yaml)
```
kubewatch itself without command/flag will start watching resources. Configs will be reflected in $HOME/.kubewatch.yaml

### CODE REVIEW

**Comment by sebgoa** [comment]
yes, that looks like what I had in mind.

is there a shorthand for deployments in kubectl ? (looks like no) maybe we could use `dep`

**Comment by ngtuna** [comment]
Two first commits wrapped up the cli exactly like this, however without inner logics.

> is there a shorthand for deployments in kubectl ? (looks like no) maybe we could use dep

Badly cobra only supports shorthand with single character. How about -d ?

**Comment by sebgoa** [comment]
sorry, I did not mean shorthand, I meant the actual flag. You abbreviate everything to the kubectl shorthand so it looks weird to have --deployments.

but that's a detail...no worries.

**Comment by ngtuna** [comment]
Yes. I was afraid of like `--replication-controller` would be too long, thus I kept abbreviating all resource names.

**Comment by ngtuna** [comment]
Merging immediately for testing. Issues will be solved in late commits.

**Pull request merged**
