### PR TITLE
hipchat support and dep as dependency tool

### PR DESCRIPTION
**Pull request by rajatjindal**
Looks like a huge PR because of dependency changes, other than that simple changes to support hipchat.

Refer to sample screenshot

screen shot 2017-10-29 at 10 37 41 pm

### CODE REVIEW

**Comment by rajatjindal83** [comment]
Kindly provide comments 

I am not quite sure about supporting >= 1.8 golang change, is that reasonable to ask?

**Comment by sebgoa** [comment]
we should move to newer version of golang anyway

just a bit concerned with that `docker/distribution` dependency, why is that needed ?

**Comment by rajatjindal83** [comment]
Its not a new dependency, following from the godeps

I can dig more whats pulling it in once i get to work

{
			"ImportPath": "github.com/docker/distribution/digest",
			"Comment": "docs-v2.4.1-2016-06-28-16-g07f32ac",
			"Rev": "07f32ac1831ed0fc71960b7da5d6bb83cb6881b5"
		},

**Comment by rajatjindal83** [comment]
coming from kubernetes client:

find . -name '*.go' | grep -v docker | xargs grep 'docker/distribution'

./vendor/k8s.io/client-go/pkg/util/parsers/parsers.go:	dockerref "github.com/docker/distribution/reference"

**Comment by rajatjindal** [comment]
@sebgoa let me know if you have more questions

**Comment by sebgoa** [comment]
no that's fine, I will merge your PR thanks a lot.

We can probably clean up a lot of the dependencies by moving to client-go

**Comment by rajatjindal** [comment]
awesome, thanks very much for merging this. 

can u let me know what do u mean by "We can probably clean up a lot of the dependencies by moving to client-go". 

may be i can try this out later this week

between, i do plan to use this in our deployment of k8s cluster. is the new image pushed automatically?

**Comment by ngtuna** [comment]
Hi @rajatjindal thank a bunch for supporting hipchat. The new image is not pushed automatically yet. I just pushed it to dockerhub at `skippbox/kubewatch:v0.0.4`. A PR for client-go will be very welcomed 👍

**Comment by ngtuna** [comment]
BTW, a switch to use `dep` is good. I am open to learn a new "vendoring" tool :-)

**Pull request merged**
